const Products = [
  {
    id: 1,
    name: 'Samsung s25 Ultra',
    brand: 'Samsung',
    category: 'Phone',
    price: 1199,
    rating: 4.8,
    tags: ['Hot', 'bestseller'],
    description: 'The latest iPhone 15 Pro with A17 chip and titanium build.',
    image: '/src/image/samsung-s25-ultra.png',
  },
  {
    id: 2,
    name: 'Google Pixel 9 Pro',
    brand: 'Google',
    category: 'Phone',
    price: 999,
    rating: 4.6,
    tags: ['Bestseller'],
    description: 'Samsung Galaxy S23 with Snapdragon 8 Gen 2 processor.',
    image: '/src/image/google-pixel-9-pro.png',
  },
  {
    id: 3,
    name: 'MacBook Pro 16”',
    brand: 'Apple',
    category: 'Laptop',
    price: 2499,
    rating: 4.9,
    tags: ['Bestseller'],
    description: 'MacBook Pro 16-inch with M2 Max chip, perfect for creators.',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8',
  },
  {
    id: 4,
    name: 'Dell XPS 13',
    brand: 'Dell',
    category: 'Laptop',
    price: 1499,
    rating: 4.5,
    tags: ['New'],
    description: 'Dell XPS 13 with InfinityEdge display and sleek design.',
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b02',
  },
  {
    id: 5,
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    category: 'Headphones',
    price: 399,
    rating: 4.7,
    tags: ['Bestseller', 'hot'],
    description: 'Industry-leading noise cancelling wireless headphones.',
    image: 'https://images.unsplash.com/photo-1585386959984-a41552231693',
  },
  {
    id: 6,
    name: 'AirPods Pro 2',
    brand: 'Apple',
    category: 'Earbuds',
    price: 249,
    rating: 4.6,
    tags: ['New'],
    description: 'Apple AirPods Pro with improved noise cancellation.',
    image: 'https://images.unsplash.com/photo-1589987607627-6f8a8cfdd6a0',
  },
  {
    id: 7,
    name: 'iPad Pro 12.9',
    brand: 'Apple',
    category: 'Tablet',
    price: 1099,
    rating: 4.7,
    tags: ['Bestseller'],
    description: 'Apple iPad Pro with M2 chip and Liquid Retina XDR display.',
    image: 'https://images.unsplash.com/photo-1593642533144-3d62aaad1a10',
  },
  {
    id: 8,
    name: 'Samsung Galaxy Tab S9',
    brand: 'Samsung',
    category: 'Tablet',
    price: 899,
    rating: 4.4,
    tags: ['New'],
    description: 'Galaxy Tab S9 with AMOLED display and S Pen included.',
    image: 'https://images.unsplash.com/photo-1606813902916-b0c3d9d6658e',
  },
  {
    id: 9,
    name: 'Apple Watch Ultra',
    brand: 'Apple',
    category: 'Wearable',
    price: 799,
    rating: 4.8,
    tags: ['Hot'],
    description: 'Apple Watch Ultra for extreme sports and adventure.',
    image: 'https://images.unsplash.com/photo-1665151965196-7c3a70b10a3c',
  },
  {
    id: 10,
    name: 'Fitbit Charge 6',
    brand: 'Fitbit',
    category: 'Wearable',
    price: 179,
    rating: 4.3,
    tags: ['Bestseller'],
    description: 'Fitbit Charge 6 fitness tracker with health monitoring.',
    image: 'https://images.unsplash.com/photo-1606813762373-77a3d2e4f2d7',
  },
  {
    id: 11,
    name: 'Canon EOS R5',
    brand: 'Canon',
    category: 'Camera',
    price: 3899,
    rating: 4.9,
    tags: ['Bestseller', 'hot'],
    description: 'Canon EOS R5 mirrorless camera with 8K video recording.',
    image: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f',
  },
  {
    id: 12,
    name: 'Nikon Z7 II',
    brand: 'Nikon',
    category: 'laptop',
    price: 2999,
    rating: 4.7,
    tags: ['Bestseller'],
    description: 'Nikon Z7 II with 45.7MP sensor and dual processors.',
    image: '/src/image/apple-macbook-pro14.png',
  },
];

export default Products;
