const Products = [
  {
    id: 1,
    name: 'Samsung s25 Ultra',
    brand: 'Samsung',
    category: 'Phone',
    price: 1299,
    rating: 4.8,
    tags: ['Hot', 'bestseller'],
    description:
      'Samsung Galaxy S25 Ultra  flagship power with Snapdragon 8 Gen 5 and S Pen.',
    image: '/src/image/samsung-s25-ultra.png',
  },
  {
    id: 2,
    name: 'Google Pixel 9 Pro',
    brand: 'Google',
    category: 'Phone',
    price: 999,
    rating: 4.6,
    tags: ['Bestseller'],
    description:
      'Google Pixel 9 Pro  Tensor G4 AI chip, and pro-grade 50 MP triple-camera magic.',
    image: '/src/image/google-pixel-9-pro.png',
  },
  {
    id: 3,
    name: 'Iphone 15 Pro Max”',
    brand: 'Apple',
    category: 'Phone',
    price: 1199,
    rating: 4.7,
    tags: ['Hot'],
    description:
      'iPhone 15 Pro Max with A17 Pro speed, titanium build, 5× optical zoom, and USB-C ready',
    image: '/src/image/iphone-16-promax.png',
  },
  {
    id: 4,
    name: 'Dell XPS 13',
    brand: 'Dell',
    category: 'Laptop',
    price: 1499,
    rating: 4.5,
    tags: ['New'],
    description: 'Dell XPS 13 with InfinityEdge display and sleek design.',
    image: '/src/image/dell-xps-13.png',
  },
  {
    id: 5,
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    category: 'Headphones',
    price: 399,
    rating: 4.7,
    tags: ['Bestseller', 'hot'],
    description: 'Industry-leading noise cancelling wireless headphones.',
    image: '/src/image/Sony-WH-1000XM5.png',
  },
  {
    id: 6,
    name: 'Apple Watch Ultra',
    brand: 'Apple',
    category: 'Wearable',
    price: 799,
    rating: 4.8,
    tags: ['Hot'],
    description: 'Apple Watch Ultra for extreme sports and adventure.',
    image: '/src/image/Apple-Watch-Ultra.png',
  },

  {
    id: 7,
    name: 'iPad Pro 12.9',
    brand: 'Apple',
    category: 'Tablet',
    price: 1099,
    rating: 4.7,
    tags: ['Bestseller'],
    description: 'Apple iPad Pro with M2 chip and Liquid Retina XDR display.',
    image: '/src/image/iPad-Pro-12.9.png',
  },
  {
    id: 8,
    name: 'Samsung Galaxy Tab S9',
    brand: 'Samsung',
    category: 'Tablet',
    price: 899,
    rating: 4.4,
    tags: ['New'],
    description: 'Galaxy Tab S9 with AMOLED display and S Pen included.',
    image: '/src/image/Samsung-Galaxy-Tab-S9.png',
  },

  {
    id: 9,
    name: 'Fitbit Charge 6',
    brand: 'Fitbit',
    category: 'Wearable',
    price: 179,
    rating: 4.3,
    tags: ['Bestseller'],
    description: 'Fitbit Charge 6 fitness tracker with health monitoring.',
    image: '/src/image/fitbit.png',
  },
  {
    id: 10,
    name: 'Canon EOS R5',
    brand: 'Canon',
    category: 'Camera',
    price: 3899,
    rating: 4.9,
    tags: ['Bestseller', 'hot'],
    description: 'Canon EOS R5 mirrorless camera with 8K video recording.',
    image: '/src/image/Canon-EOS-R5.png',
  },
  {
    id: 11,
    name: 'Apple Macbook Pro 14',
    brand: 'Apple',
    category: 'laptop',
    price: 1999,
    rating: 4.8,
    tags: ['Bestseller'],
    description:
      'MacBook Pro 14-inch — M3 Pro power, Liquid Retina XDR brilliance, all-day battery.',
    image: '/src/image/apple-macbook-pro14.png',
  },
  {
    id: 12,
    name: 'AirPods Pro 2',
    brand: 'Apple',
    category: 'Earbuds',
    price: 249,
    rating: 4.6,
    tags: ['New'],
    description: 'Apple AirPods Pro with improved noise cancellation.',
    image: '/src/image/AirPods-Pro-2.png',
  },
];

export default Products;
